// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.18.0
// source: getMax.proto

package getMax

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num1 int32 `protobuf:"varint,1,opt,name=num1,proto3" json:"num1,omitempty"`
	Num2 int32 `protobuf:"varint,2,opt,name=num2,proto3" json:"num2,omitempty"`
}

func (x *GetMaxRequest) Reset() {
	*x = GetMaxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getMax_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxRequest) ProtoMessage() {}

func (x *GetMaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getMax_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxRequest.ProtoReflect.Descriptor instead.
func (*GetMaxRequest) Descriptor() ([]byte, []int) {
	return file_getMax_proto_rawDescGZIP(), []int{0}
}

func (x *GetMaxRequest) GetNum1() int32 {
	if x != nil {
		return x.Num1
	}
	return 0
}

func (x *GetMaxRequest) GetNum2() int32 {
	if x != nil {
		return x.Num2
	}
	return 0
}

type GetMaxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxNum int32 `protobuf:"varint,1,opt,name=maxNum,proto3" json:"maxNum,omitempty"`
}

func (x *GetMaxResponse) Reset() {
	*x = GetMaxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getMax_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMaxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMaxResponse) ProtoMessage() {}

func (x *GetMaxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_getMax_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMaxResponse.ProtoReflect.Descriptor instead.
func (*GetMaxResponse) Descriptor() ([]byte, []int) {
	return file_getMax_proto_rawDescGZIP(), []int{1}
}

func (x *GetMaxResponse) GetMaxNum() int32 {
	if x != nil {
		return x.MaxNum
	}
	return 0
}

type GetListMaxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nums []int32 `protobuf:"varint,1,rep,packed,name=nums,proto3" json:"nums,omitempty"`
}

func (x *GetListMaxRequest) Reset() {
	*x = GetListMaxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_getMax_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListMaxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListMaxRequest) ProtoMessage() {}

func (x *GetListMaxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_getMax_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListMaxRequest.ProtoReflect.Descriptor instead.
func (*GetListMaxRequest) Descriptor() ([]byte, []int) {
	return file_getMax_proto_rawDescGZIP(), []int{2}
}

func (x *GetListMaxRequest) GetNums() []int32 {
	if x != nil {
		return x.Nums
	}
	return nil
}

var File_getMax_proto protoreflect.FileDescriptor

var file_getMax_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x22, 0x37, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x75, 0x6d, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x75, 0x6d, 0x32, 0x22,
	0x28, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x4e, 0x75, 0x6d, 0x22, 0x27, 0x0a, 0x11, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x75, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x75,
	0x6d, 0x73, 0x32, 0x81, 0x01, 0x0a, 0x06, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x12, 0x38, 0x0a,
	0x07, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x77, 0x6f, 0x12, 0x15, 0x2e, 0x67, 0x65, 0x74, 0x4d, 0x61,
	0x78, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x4d, 0x61, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x65, 0x74, 0x4d, 0x61, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_getMax_proto_rawDescOnce sync.Once
	file_getMax_proto_rawDescData = file_getMax_proto_rawDesc
)

func file_getMax_proto_rawDescGZIP() []byte {
	file_getMax_proto_rawDescOnce.Do(func() {
		file_getMax_proto_rawDescData = protoimpl.X.CompressGZIP(file_getMax_proto_rawDescData)
	})
	return file_getMax_proto_rawDescData
}

var file_getMax_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_getMax_proto_goTypes = []interface{}{
	(*GetMaxRequest)(nil),     // 0: getMax.GetMaxRequest
	(*GetMaxResponse)(nil),    // 1: getMax.GetMaxResponse
	(*GetListMaxRequest)(nil), // 2: getMax.GetListMaxRequest
}
var file_getMax_proto_depIdxs = []int32{
	0, // 0: getMax.getMax.fromTwo:input_type -> getMax.GetMaxRequest
	2, // 1: getMax.getMax.fromList:input_type -> getMax.GetListMaxRequest
	1, // 2: getMax.getMax.fromTwo:output_type -> getMax.GetMaxResponse
	1, // 3: getMax.getMax.fromList:output_type -> getMax.GetMaxResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_getMax_proto_init() }
func file_getMax_proto_init() {
	if File_getMax_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_getMax_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getMax_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMaxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_getMax_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListMaxRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_getMax_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_getMax_proto_goTypes,
		DependencyIndexes: file_getMax_proto_depIdxs,
		MessageInfos:      file_getMax_proto_msgTypes,
	}.Build()
	File_getMax_proto = out.File
	file_getMax_proto_rawDesc = nil
	file_getMax_proto_goTypes = nil
	file_getMax_proto_depIdxs = nil
}
